// <auto-generated />
namespace StanOK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class postgres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postgres));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:StanOK/Migrations/202305311635291_postgres.Designer.cs
            get { return "202305311635291_postgres"; }
========
            get { return "202306020637215_postgres"; }
>>>>>>>> 7a634a7fff73e013cd423b931c4209633fb66be9:StanOK/Migrations/202306020637215_postgres.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
