// <auto-generated />
namespace StanOK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class postgres1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postgres1));
        
        string IMigrationMetadata.Id
        {
            get { return "202305281237124_postgres1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
